import { StyleSheet, Platform } from 'react-native';

import {
  scale,
  moderateScale,
  moderateVerticalScale,
} from 'react-native-size-matters';

import Colors from '../../Styles/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  subContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  detailContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  modalStyle: {
    margin: 0,
    justifyContent: 'flex-end',
  },
  categoryCardStyle: {
    width: moderateScale(150),
    height: moderateVerticalScale(150),
    borderRadius: moderateScale(56),
    backgroundColor: '#F8FAFC',
    margin: moderateScale(12),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: moderateVerticalScale(40),
    marginBottom: moderateVerticalScale(-20),
  },
  categoryImgtyle: {
    width: moderateScale(70),
    height: moderateVerticalScale(70),
  },
  categoryTexttyle: {
    fontWeight: '500',
    fontSize: scale(15),
    margin: moderateScale(8),
    color: Colors.blackOpacity75,
  },
  categoryTextStyle: {
    width: '85%',
    fontWeight: '500',
    fontSize: scale(15),
    margin: moderateScale(8),
    color: Colors.blackOpacity75,
  },
  categoryTextTwoStyle: {
    width: '76%',
    fontWeight: '500',
    fontSize: scale(13.5),
    margin: moderateScale(8),
    color: Colors.blackOpacity75,
    // marginTop: moderateVerticalScale(30),
  },
  subCategoryCardStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    marginTop: moderateVerticalScale(14),
    margin: moderateScale(12),
    marginBottom: moderateVerticalScale(5),
    width: moderateScale(330),
    height: moderateVerticalScale(100),
    shadowColor: Platform.OS === 'ios' ? 'rgba(0, 0, 0, 0.25)' : 'black',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: Platform.OS === 'ios' ? 5 : 2,
    elevation: 5,
  },
  subCategoryImgStyle: {
    marginStart: moderateScale(14),
    width: moderateScale(70),
    height: moderateVerticalScale(70),
  },
  subCategoryTexttyle: {
    fontWeight: '500',
    fontSize: scale(15),
    color: Colors.blackOpacity80,
  },
  subCategoryRightViewStyle: {
    width: moderateScale(70),
    height: moderateVerticalScale(100),
    backgroundColor: Colors.theme,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subCategoryRightImgStyle: {
    width: moderateScale(26),
    height: moderateVerticalScale(11),
  },
  rightTitleStyle: {
    color: Colors.blackOpacity50,
    fontWeight: '500',
    fontSize: scale(14),
  },
  resultStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: moderateVerticalScale(44),
    backgroundColor: Colors.whiteOpacity25,
  },
  resultTextStyle: {
    fontWeight: '400',
    fontSize: scale(13),
    color: Colors.blackOpacity75,
    marginHorizontal: moderateScale(12.5),
  },
  locationTextStyle: {
    width: '66%',
    fontWeight: '400',
    fontSize: scale(13),
    color: Colors.blackOpacity75,
    marginHorizontal: moderateScale(10),
    marginTop: moderateVerticalScale(-3),
  },
  listReviewStyle: {
    fontWeight: '400',
    fontSize: scale(12),
    color: Colors.blackOpacity75,
    marginHorizontal: moderateScale(10),
    marginBottom: moderateScale(8),
  },
  listAddressStyle: {
    fontWeight: '400',
    fontSize: scale(12),
    color: Colors.blackOpacity75,
    marginHorizontal: moderateScale(10),
  },
  iconViewStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: moderateScale(5),
  },
  resultIcOneStyle: {
    width: moderateScale(18),
    height: moderateVerticalScale(18),
  },
  resultIcTwoStyle: {
    width: moderateScale(15),
    height: moderateVerticalScale(15),
    marginHorizontal: moderateScale(10),
  },
  lineIcStyle: {
    width: moderateScale(18),
    height: moderateVerticalScale(18),
    marginHorizontal: moderateScale(7),
    marginTop: moderateVerticalScale(10),
  },
  deatilCategoryCardStyle: {
    backgroundColor: Colors.white,
    margin: moderateScale(12),
    marginBottom: moderateVerticalScale(10),
    shadowColor: Platform.OS === 'ios' ? 'rgba(0, 0, 0, 0.25)' : 'black',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: Platform.OS === 'ios' ? 5 : 2,
    elevation: 5,
  },
  deatilCategoryCardTwoStyle: {
    backgroundColor: Colors.white,
    margin: moderateScale(12),
    marginBottom: moderateVerticalScale(10),
    shadowColor: Platform.OS === 'ios' ? 'rgba(0, 0, 0, 0.25)' : 'black',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: Platform.OS === 'ios' ? 5 : 2,
    elevation: 5,
  },
  detailCategoryImgtyle: {
    width: '100%',
    height: moderateVerticalScale(150),
  },
  detailCategoryImgTwoStyle: {
    width: moderateScale(140),
    height: moderateVerticalScale(135),
    borderRadius: moderateScale(4),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(15),
  },
  detailCategoryDescThreeStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(5),
  },
  detailCategoryDescStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(5),
  },
  detailCategoryDescTwoStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  lineStyle: {
    width: '90.8%',
    alignSelf: 'center',
    margin: moderateScale(15),
    height: moderateVerticalScale(1),
    backgroundColor: Colors.whiteOpacity50,
  },
  listLineStyle: {
    width: '85%',
    margin: moderateScale(10),
    height: moderateVerticalScale(1),
    backgroundColor: Colors.whiteOpacity50,
  },
  addressViewStyle: {
    flexDirection: 'row',
  },
  detailCategoryVerifiedViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: moderateScale(10),
  },
  listMainViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailCategoryVerifiedViewTwoStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: moderateScale(10),
    marginBottom: moderateVerticalScale(10),
  },
  locationIcStyle: {
    width: moderateScale(16),
    height: moderateVerticalScale(16),
    marginStart: moderateScale(8),
    marginEnd: moderateScale(-5),
  },
  verifiedIcStyle: {
    width: moderateScale(25),
    height: moderateVerticalScale(25),
  },
  verifiedIcTwoStyle: {
    width: moderateScale(16),
    height: moderateVerticalScale(16),
  },
  verifiedTextStyle: {
    color: '#4EBA09',
    fontWeight: '500',
    fontSize: scale(15),
    marginHorizontal: moderateScale(9),
  },
  verifiedTextTwoStyle: {
    color: '#4EBA09',
    fontWeight: '500',
    fontSize: scale(13.5),
    marginHorizontal: moderateScale(9),
  },
  listViewStyle: {
    width: '57.2%',
    marginStart: moderateScale(-7.5),
  },
  ratingViewStyle: {
    width: '13.5%',
    height: moderateScale(25),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4EBA09',
    margin: moderateScale(5),
    borderRadius: moderateScale(2),
  },
  ratingViewTwoStyle: {
    width: '32.5%',
    height: moderateScale(25),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4EBA09',
    margin: moderateScale(5),
    borderRadius: moderateScale(2),
  },
  ratingIcStyle: {
    width: moderateScale(12),
    height: moderateVerticalScale(12),
    marginHorizontal: moderateScale(2.5),
  },
  ratingTextStyle: {
    fontWeight: '400',
    fontSize: scale(12),
    color: Colors.white,
    marginHorizontal: moderateScale(2.5),
  },
  bottomBtnViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  labelStyle: {
    color: Colors.darkBlack,
    fontWeight: '500',
    fontSize: scale(14),
    top: moderateVerticalScale(-10),
  },
  buttonStyle: {
    width: '49.9%',
    height: moderateVerticalScale(80),
    backgroundColor: Colors.theme,
  },
  offerDetailsContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  imageBgStyle: {
    width: '100%',
    height: moderateVerticalScale(165),
  },
  cardWithShadowStyle: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: Colors.white,
    top: moderateVerticalScale(-25),
    shadowColor: Platform.OS === 'ios' ? 'rgba(0, 0, 0, 0.25)' : 'black',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: Platform.OS === 'ios' ? 5 : 2,
    elevation: 5,
  },
  locationPinStyle: {
    width: moderateScale(15),
    height: moderateVerticalScale(15),
  },
  cardLocationTextStyle: {
    width: moderateScale(180),
    color: Colors.blackOpacity75,
    fontWeight: '400',
    fontSize: scale(13),
    marginHorizontal: moderateScale(5),
  },
  priceTextStyle: {
    width: moderateScale(90),
    color: Colors.green,
    fontWeight: '500',
    fontSize: scale(14),
    textAlign: 'center',
  },
  lineHorizontalViewStyle: {
    width: '90%',
    height: moderateVerticalScale(1),
    alignSelf: 'center',
    backgroundColor: Colors.whiteOpacity50,
  },
  lineHorizontalViewTwoStyle: {
    width: '85%',
    height: moderateVerticalScale(1),
    alignSelf: 'center',
    marginBottom: moderateVerticalScale(20),
    backgroundColor: Colors.whiteOpacity50,
    marginTop: moderateVerticalScale(10),
  },
  lineVeritcalViewStyle: {
    width: moderateVerticalScale(1),
    height: moderateVerticalScale(45),
    top: moderateScale(10),
    backgroundColor: Colors.whiteOpacity50,
  },
  cardlabelStyle: {
    color: Colors.darkBlack,
    fontWeight: '400',
    fontSize: scale(13),
  },
  leftIconStyle: {
    width: moderateScale(21),
    height: moderateVerticalScale(21),
  },
  galleryReviewViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    margin: moderateScale(10),
    marginStart: moderateScale(15),
    marginEnd: moderateScale(15),
    top: moderateScale(10),
  },
  galleryButtonStyle: {
    width: moderateScale(130),
    height: moderateVerticalScale(45),
    backgroundColor: Colors.whiteOpacity75,
    borderRadius: moderateScale(39),
    borderBottomLeftRadius: 0,
  },
  AddReviewButtonStyle: {
    width: moderateScale(130),
    height: moderateVerticalScale(45),
    backgroundColor: Colors.themeOpacity25,
    borderRadius: moderateScale(39),
    borderBottomRightRadius: 0,
  },
  reviewTextStyle: {
    color: Colors.blackOpacity75,
    fontWeight: '400',
    fontSize: scale(13),
  },
  viewStyle: {
    width: '50%',
    alignItems: 'center',
    top: moderateVerticalScale(10),
    marginBottom: moderateVerticalScale(20),
  },
  tabBtnStyle: {
    width: '50%',
    height: moderateVerticalScale(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabTextStyle: {
    color: Colors.blackOpacity80,
    fontWeight: '500',
    fontSize: scale(14),
  },
  indicatorStyle: {
    width: '45%',
    height: moderateVerticalScale(2),
    backgroundColor: Colors.theme,
    position: 'absolute',
  },
  teamGreyStyle: {
    flexDirection: 'row',
    height: moderateVerticalScale(44),
    backgroundColor: Colors.whiteOpacity30,
    marginBottom: moderateVerticalScale(20),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  teamTextStyle: {
    color: Colors.blackOpacity80,
    fontWeight: '500',
    fontSize: scale(14),
    left: moderateScale(20),
  },
  teamFlexStyle: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: moderateVerticalScale(30),
  },
  teamImgBgStyle: {
    width: moderateScale(96),
    height: moderateVerticalScale(83),
    backgroundColor: Colors.whiteOpacity30,
    marginBottom: moderateVerticalScale(30),
  },
  teamUserImgStyle: {
    width: moderateScale(80),
    height: moderateVerticalScale(80),
    alignSelf: 'center',
    marginBottom: moderateVerticalScale(10),
  },
  teamUserTextStyle: {
    color: Colors.blackOpacity75,
    fontWeight: '500',
    fontSize: scale(13),
  },
  teamUserProfTextStyle: {
    color: Colors.blackOpacity75,
    fontWeight: '400',
    fontSize: scale(12),
  },
  viewMoreTextStyle: {
    color: Colors.green,
    fontWeight: '500',
    fontSize: scale(13),
    // right: moderateScale(20),
  },
  pTagStyle: {
    color: Colors.blackOpacity75,
    fontWeight: '400',
    fontSize: scale(13),
    textAlign: 'justify',
    marginHorizontal: moderateScale(15),
  },
  offersTabView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginHorizontal: moderateScale(15),
    marginTop: moderateVerticalScale(-12),
  },
  descriptionStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: moderateScale(10),
    marginStart: moderateScale(15),
    marginEnd: moderateScale(15),
  },
  desItemsStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scrollViewStyle: {
    flex: 1,
  },
  galleryImgStyle: {
    width: moderateScale(149),
    height: moderateVerticalScale(112),
  },
  galleryTextViewStyle: {
    width: moderateScale(149),
    height: moderateVerticalScale(34),
    backgroundColor: Colors.whiteOpacity30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  blurGalleryImgStyle: {
    top: moderateVerticalScale(-112),
    width: moderateScale(149),
    height: moderateVerticalScale(112),
    backgroundColor: '#ffffff60',
    alignItems: 'center',
    justifyContent: 'center',
    ...StyleSheet.absoluteFillObject,
  },
  shortListTextStyle: {
    color: Colors.white,
    fontWeight: '500',
    fontSize: scale(14),
  },
  shortListButtonStyle: {
    width: '50%',
    height: moderateVerticalScale(80),
    backgroundColor: Colors.darkBlack,
  },
  ContactButtonStyle: {
    width: '50%',
    height: moderateVerticalScale(80),
    backgroundColor: Colors.theme,
  },
  iconStyle: {
    tintColor: Colors.white,
  },
  reviewCardStyle: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    marginBottom: moderateVerticalScale(20),
    shadowColor: Platform.OS === 'ios' ? 'rgba(0, 0, 0, 0.25)' : 'black',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: Platform.OS === 'ios' ? 5 : 2,
    elevation: 5,
  },
  reviewImgViewStyle: {
    shadowColor: Platform.OS === 'ios' ? 'rgba(0, 0, 0, 0.25)' : 'black',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: Platform.OS === 'ios' ? 5 : 2,
    elevation: 5,
    borderRadius: 360,
    backgroundColor: Colors.white,
    marginStart: moderateScale(20),
    marginEnd: moderateScale(10),
  },
  reviewImgStyle: {
    width: moderateScale(68),
    height: moderateVerticalScale(68),
    alignSelf: 'center',
    borderRadius: 360,
    margin: moderateVerticalScale(10),
  },
  reviewContentStyle: {
    width: '61%',
    marginTop: moderateVerticalScale(10),
    marginBottom: moderateVerticalScale(10),
  },
  ratingStyle: {
    marginTop: moderateVerticalScale(-30),
    marginLeft: moderateScale(-120),
    marginBottom: moderateVerticalScale(10),
  },
  descriptionTextStyle: {
    color: Colors.blackOpacity75,
    fontWeight: '400',
    fontSize: scale(13),
    marginTop: moderateVerticalScale(10),
    marginHorizontal: moderateScale(30),
    marginBottom: moderateVerticalScale(10),
  },
  faqViewStyle: {
    marginTop: moderateVerticalScale(-10),
    marginBottom: moderateVerticalScale(20),
  },
  addImgStyle: {
    width: moderateScale(15),
    height: moderateVerticalScale(15),
    marginEnd: moderateScale(-50),
  },
  addIconBtnStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: moderateScale(100),
    height: moderateVerticalScale(44),
  },
  highlightStyle: {
    borderTopStartRadius: moderateScale(4),
    borderTopEndRadius: moderateScale(4),
    backgroundColor: Colors.theme,
    height: moderateVerticalScale(8),
  },
  moreInfoViewStyle: {
    alignSelf: 'center',
    backgroundColor: Colors.white,
    width: moderateScale(300),
    borderTopStartRadius: moderateScale(4),
    borderTopEndRadius: moderateScale(4),
    borderBottomStartRadius: moderateScale(4),
    borderBottomEndRadius: moderateScale(4),
  },
  inputStyle: {
    borderRadius: 0,
    margin: moderateScale(5),
    top: 8,
    elevation: 0,
    color: 'red',
    backgroundColor: Colors.white,
  },
  submitBtnStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    height: moderateVerticalScale(40),
    backgroundColor: Colors.theme,
    marginTop: moderateVerticalScale(35),
    borderBottomStartRadius: moderateScale(4),
    borderBottomEndRadius: moderateScale(4),
  },
  submitlabelStyle: {
    fontWeight: '500',
    fontSize: scale(13),
    color: Colors.blackOpacity80,
  },
  marginTop30Style: {
    marginTop: moderateVerticalScale(30),
  },
  moreInfoStyle: {
    flexDirection: 'row',
    marginBottom: moderateVerticalScale(20),
    marginHorizontal: moderateScale(20),
  },
  moreInfoTitleStyle: {
    flex: 1,
    fontWeight: '600',
    color: Colors.darkBlack,
  },
  moreInfoDescStyle: {
    flex: 2,
    fontWeight: '400',
    color: Colors.blackOpacity80,
  },
  moreInfoDeleteBtnStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: moderateScale(30),
    height: moderateVerticalScale(30),
    marginEnd: moderateScale(-10),
  },
  moreInfoDeleteIcStyle: {
    width: moderateScale(15),
    height: moderateVerticalScale(15),
  },
});

export default styles;
