export default {
  /*** Declare Types For Api's Call Here... ***/
  USER_TOKEN: 'USER_TOKEN',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  SNACK_BAR: 'SNACK_BAR',
  RESET_APP: 'RESET_APP',
  APP_LOADER: 'APP_LOADER',

  ADD_TO_WALLET: 'ADD_TO_WALLET',
  ADD_TO_WALLET_SUCCESS: 'ADD_TO_WALLET_SUCCESS',


  SEND_PAYMENT_RESPONSE: 'SEND_PAYMENT_RESPONSE',
  SEND_PAYMENT_RESPONSE_SUCCESS: 'SEND_PAYMENT_RESPONSE_SUCCESS',

  LOGIN_OTP_VERIFY: 'LOGIN_OTP_VERIFY',
  LOGIN_OTP_VERIFY_SUCCESS: 'LOGIN_OTP_VERIFY_SUCCESS',

  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  CUSTOMER_SUPPORT_SUCCESS: 'CUSTOMER_SUPPORT_SUCCESS',

  FEEDBACK: 'FEEDBACK',
  FEEDBACK_SUCCESS: 'FEEDBACK_SUCCESS',

  GET_VENDOR_LIST: 'GET_VENDOR_LIST',
  GET_VENDOR_LIST_SUCCESS: 'GET_VENDOR_LIST_SUCCESS',

  VENDOR_DETAILS: 'VENDOR_DETAILS',
  VENDOR_DETAILS_SUCCESS: 'VENDOR_DETAILS_SUCCESS',

  GET_FAQ: 'GET_FAQ',
  GET_FAQ_SUCCESS: 'GET_FAQ_SUCCESS',

  GET_VENDOR_GALLERY: 'GET_VENDOR_GALLERY',
  GET_VENDOR_GALLERY_SUCCESS: 'GET_VENDOR_GALLERY_SUCCESS',

  DELETE_VENDOR_GALLERY: 'DELETE_VENDOR_GALLERY',

  GET_VENDOR_VIDEO: 'GET_VENDOR_VIDEO',
  GET_VENDOR_VIDEO_SUCCESS: 'GET_VENDOR_VIDEO_SUCCESS',
  ADD_VENDOR_VIDEO: 'ADD_VENDOR_VIDEO',
  ADD_VENDOR_VIDEO_SUCCESS: 'ADD_VENDOR_VIDEO_SUCCESS',
  DELETE_VENDOR_VIDEO: 'DELETE_VENDOR_VIDEO',
  DELETE_VENDOR_VIDEO_SUCCESS: 'DELETE_VENDOR_VIDEO_SUCCESS',

  GET_VENDOR_ALBUM: 'GET_VENDOR_ALBUM',
  GET_VENDOR_ALBUM_SUCCESS: 'GET_VENDOR_ALBUM_SUCCESS',
  ADD_VENDOR_ALBUM: 'ADD_VENDOR_ALBUM',
  DELETE_VENDOR_ALBUM: 'DELETE_VENDOR_ALBUM',
  DELETE_VENDOR_ALBUM_IMAGE: 'DELETE_VENDOR_ALBUM_IMAGE',

  GET_VENDOR_PRICE: 'GET_VENDOR_PRICE',
  GET_VENDOR_PRICE_SUCCESS: 'GET_VENDOR_PRICE_SUCCESS',
  ADD_VENDOR_PRICE: 'ADD_VENDOR_PRICE',
  DELETE_VENDOR_PRICE: 'DELETE_VENDOR_PRICE',
  DELETE_VENDOR_PRICE_IMAGE: 'DELETE_VENDOR_PRICE_IMAGE',

  GET_VENDOR_MORE_INFO: 'GET_VENDOR_MORE_INFO',
  GET_VENDOR_MORE_INFO_SUCCESS: 'GET_VENDOR_MORE_INFO_SUCCESS',
  ADD_VENDOR_MORE_INFO: 'ADD_VENDOR_MORE_INFO',
  ADD_VENDOR_MORE_INFO_SUCCESS: 'ADD_VENDOR_MORE_INFO_SUCCESS',
  DELETE_VENDOR_MORE_INFO: 'DELETE_VENDOR_MORE_INFO',
  DELETE_VENDOR_MORE_INFO_SUCCESS: 'DELETE_VENDOR_MORE_INFO_SUCCESS',

  GET_VENDOR_FAQ: 'GET_VENDOR_FAQ',
  GET_VENDOR_FAQ_SUCCESS: 'GET_VENDOR_FAQ_SUCCESS',
  ADD_VENDOR_FAQ: 'ADD_VENDOR_FAQ',
  ADD_VENDOR_FAQ_SUCCESS: 'ADD_VENDOR_FAQ_SUCCESS',
  DELETE_VENDOR_FAQ: 'DELETE_VENDOR_FAQ',
  DELETE_VENDOR_FAQ_SUCCESS: 'DELETE_VENDOR_FAQ_SUCCESS',

  GET_VENDOR_OFFERS: 'GET_VENDOR_OFFERS',
  GET_VENDOR_OFFERS_SUCCESS: 'GET_VENDOR_OFFERS_SUCCESS',
  ADD_VENDOR_OFFERS: 'ADD_VENDOR_OFFERS',
  ADD_VENDOR_OFFERS_SUCCESS: 'ADD_VENDOR_OFFERS_SUCCESS',
  DELETE_VENDOR_OFFERS: 'DELETE_VENDOR_OFFERS',
  DELETE_VENDOR_OFFERS_SUCCESS: 'DELETE_VENDOR_OFFERS_SUCCESS',

  /*** Declare Types For Local Dispatch Actions Here... ***/
};
